AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for circuit breaker pattern

Resources:
  QueueForError:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: circuit-breaker-error-queue
  CircuitBreakerStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      Type: STANDARD
      Name: circuitbreaker-statemachine
      DefinitionUri: statemachine/circuitbreaker.asl.json
      DefinitionSubstitutions:
        GetCircuitStatusFunctionArn: !GetAtt GetCircuitStatusFunction.Arn
        UpdateCircuitStatusFunctionArn: !GetAtt UpdateCircuitStatusFunction.Arn
        DDBPutItem: !Sub arn:${AWS::Partition}:states:::dynamodb:putItem
        DDBTable: !Ref CircuitBreakerTable
        ErrorQueue: !Ref QueueForError
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - AWSLambdaRole
        - DynamoDBWritePolicy:
            TableName: !Ref CircuitBreakerTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt QueueForError.QueueName

  GetCircuitStatusFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: circuitbreaker-GetCircuitStatus
      CodeUri: ./GetCircuitStatusLambda
      Handler: app.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
        - AWSXrayFullAccess
        - AWSStepFunctionsFullAccess


  UpdateCircuitStatusFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: circuitbreaker-UpdateCircuitStatus
      CodeUri: ./UpdateCircuitStatusLambda/
      Handler: UpdateCircuitStatusLambda::UpdateCircuitStatusLambda.UpdateCircuitStatus::FunctionHandler
      Handler: app.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
        - AWSXrayFullAccess
        - AWSStepFunctionsFullAccess      

  PaymentTimeoutFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: circuitbreaker-PaymentTimeout
      CodeUri: ./PaymentTimeout
      Handler: app.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 30
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
        - AWSXrayFullAccess
        - AWSStepFunctionsFullAccess
  
  PaymentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: circuitbreaker-Payment
      CodeUri: ./Payment
      Handler: app.lambda_handler
      Runtime: python3.11
      MemorySize: 128
      Timeout: 30
      Policies:
        - AmazonDynamoDBFullAccess
        - CloudWatchLogsFullAccess
        - AWSXrayFullAccess
        - AWSStepFunctionsFullAccess


  CircuitBreakerTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CircuitBreakerPython
      KeySchema:
        - AttributeName: ServiceName
          KeyType: HASH
        - AttributeName: ExpireTimeStamp
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: ServiceName
          AttributeType: S
        - AttributeName: ExpireTimeStamp
          AttributeType: N
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ExpireTimeStamp
        Enabled: true
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
      
